In [1]:
import pandas as pd
df=pd.read_csv('C:\\Users\\adity\\OneDrive\\Desktop\\plastics.csv')

In [2]:
df.head()

2cm   4cm   6cm   8cm  10cm Label
0  88.0  69.5  53.0  41.0  35.0    PP
1  80.0  62.0  49.0  39.0  34.0    PP
2  89.0  65.0  50.0  41.0  34.5  HDPE
3  85.5  60.0  43.5  37.0  30.0  HDPE
4  92.0  68.0  49.0  39.5  32.0  HDPE

In [3]:
d={'PP':0,'HDPE':1,'PET':2 }
df['Label']=df['Label'].map(d)

In [4]:
import numpy as np
x=df[['2cm','4cm','6cm','8cm','10cm']]
y=df[['Label']]

In [5]:
from sklearn.preprocessing import MinMaxScaler,StandardScaler
#scaling=MinMaxScaler(feature_range=(-1,1)).fit(x)
scaling=StandardScaler()
x=scaling.fit_transform(x)

In [6]:

y

Label
0       0
1       0
2       1
3       1
4       1
5       2
6       2
7       2
8       2
9       2
10      2
11      2
12      2
13      2
14      2
15      1
16      1
17      1
18      1
19      1
20      1
21      1
22      0
23      0
24      0
25      0
26      0
27      0
28      0
29      0

In [7]:
x


array([[ 0.89771336,  1.06696255,  1.20180506,  0.28860869,  0.87608519],
       [ 0.26865874,  0.27072184,  0.59200968,  0.04641958,  0.59009438],
       [ 0.97634519,  0.58921812,  0.74445853,  0.28860869,  0.73308978],
       [ 0.70113379,  0.05839099, -0.24645897, -0.19576953, -0.55386887],
       [ 1.21224067,  0.90771441,  0.59200968,  0.10696686,  0.01811275],
       [-1.42192554, -1.21559415, -1.54227415, -1.04343142, -1.41184131],
       [-1.50055737, -1.42792501, -1.61849858, -1.22507325, -1.55483672],
       [-1.26466188, -1.53409043, -1.08492762, -0.92233686, -1.1258505 ],
       [-1.38260962, -1.37484229, -1.38982531, -1.16452598, -1.41184131],
       [-1.22534597, -1.26867686, -1.23737646, -1.16452598, -0.98285509],
       [-1.34329371, -1.64025586, -1.08492762, -1.34616781, -0.83985969],
       [-1.46124145, -1.21559415, -1.16115204, -1.28562053, -0.83985969],
       [-1.3039778 , -1.48100772, -1.31360088, -1.28562053, -1.41184131],
       [-1.50055737, -1.21559415, -1.2

In [8]:
y=np.array(y)
y

array([[0],
       [0],
       [1],
       [1],
       [1],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]], dtype=int64)

In [9]:
trainX=x[:int(len(x)*0.8)]
trainY=y[:int(len(y)*0.8)]
testX=x[int(len(x)*0.8):]
testY=y[int(len(y)*0.8):]

In [10]:
from sklearn import svm, datasets
C=1.0
#svc=svm.SVC(kernel='linear',C=C).fit(x, y)
svc=svm.NuSVC(gamma="auto").fit(trainX,trainY)

d:\Anaconda\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [11]:
import pickle
pickle.dump(svc, open('model1.sav','wb'))

In [12]:
#for i in range(0,int(len(y)*0.2)):
print(y, svc.predict(scaling.transform(x)))

[[0]
 [0]
 [1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]] [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


d:\Anaconda\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [13]:
print(svc.predict(scaling.transform(np.array([]))))

d:\Anaconda\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


ValueError: Expected 2D array, got 1D array instead:
array=[].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [ ]:
print(y)

[[0]
 [0]
 [1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]


In [15]:
from sklearn import metrics
predY=svc.predict(scaling.transform(x))
# Model Accuracy: how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y, predY))

Accuracy: 0.3333333333333333


d:\Anaconda\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [23]:
print(testY, predY)

[[0]
 [0]
 [0]
 [0]
 [0]
 [0]] [0 1 1 1 1 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0]


In [25]:
import pandas as pd
df2=pd.read_csv('C:\\Users\\adity\\OneDrive\\Desktop\\plastics.csv')

In [26]:
x=df2[['2cm','4cm','6cm','8cm','10cm']]
y=df2[['Label']]
print(x,y)

     2cm   4cm   6cm   8cm  10cm
0   88.0  69.5  53.0  41.0  35.0
1   80.0  62.0  49.0  39.0  34.0
2   89.0  65.0  50.0  41.0  34.5
3   85.5  60.0  43.5  37.0  30.0
4   92.0  68.0  49.0  39.5  32.0
5   58.5  48.0  35.0  30.0  27.0
6   57.5  46.0  34.5  28.5  26.5
7   60.5  45.0  38.0  31.0  28.0
8   59.0  46.5  36.0  29.0  27.0
9   61.0  47.5  37.0  29.0  28.5
10  59.5  44.0  38.0  27.5  29.0
11  58.0  48.0  37.5  28.0  29.0
12  60.0  45.5  36.5  28.0  27.0
13  57.5  48.0  37.0  29.5  27.5
14  58.5  47.0  38.0  28.0  27.0
15  87.5  64.0  48.0  38.0  33.5
16  86.0  63.5  48.0  37.5  32.5
17  90.0  64.5  47.5  39.0  31.0
18  87.0  65.5  47.0  42.0  33.0
19  88.5  64.0  46.5  39.0  34.5
20  86.0  66.5  44.0  38.5  31.5
21  86.5  67.0  43.5  38.0  32.0
22  82.0  65.0  52.5  49.0  36.0
23  83.5  71.0  55.0  49.5  34.5
24  84.0  69.0  53.5  50.0  36.6
25  84.0  69.5  54.0  50.0  35.0
26  82.0  64.5  48.0  51.5  35.5
27  81.5  64.0  51.0  51.0  37.0
28  81.0  67.0  51.0  49.5  37.5
29  83.5  